FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install flask-debug watchdog

# Copy the application code
COPY . .

EXPOSE 5000

# Command to run the Flask app
CMD ["python", "run.py", "--host", "0.0.0.0", "--debug"]
