version: '3.8'

services:
  web_prod:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"  
    env_file:
      - .env.prod
    depends_on:
      - db_prod
    networks:
      - flask_prod_network

  db_prod:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask_prod_network

networks:
  flask_prod_network:
    driver: bridge

volumes:
  postgres_data:

