name: Deploy to Linode

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create production env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env.prod
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env.prod
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.prod
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.prod
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.prod

      - name: Copy application files to Linode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_SSH_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          source: ".,!venv,!.git,!__pycache__,!*.pyc"
          target: "/home/${{ secrets.LINODE_SSH_USER }}/zelo_website"
          rm: true
          strip_components: 0

      - name: Configure Docker on Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_SSH_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            # Create a temporary sudoers file
            echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/temp_docker_setup
            
            # Now we can use sudo without password
            sudo usermod -aG docker $USER
            sudo chown root:docker /var/run/docker.sock
            sudo chmod 666 /var/run/docker.sock
            sudo systemctl restart docker
            
            # Remove the temporary sudoers file
            sudo rm /etc/sudoers.d/temp_docker_setup

      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_SSH_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            # Move to project directory
            cd /home/${{ secrets.LINODE_SSH_USER }}/zelo_website
            
            # Setup environment
            mv .env.prod .env
            
            # Wait for Docker to be ready
            sleep 5
            
            # Try to use Docker directly (should work now with socket permissions)
            docker ps >/dev/null 2>&1 || { echo "Docker is not accessible. Please check permissions."; exit 1; }
            docker-compose down --remove-orphans || true
            docker-compose up --build -d