name: Deploy to Linode

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/${{ secrets.LINODE_SSH_USER }}/.github/workflows

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures 'deploy' runs only after 'build' finishes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.LINODE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Linode to Known Hosts
        run: ssh-keyscan -H ${{ secrets.LINODE_IP }} >> ~/.ssh/known_hosts

      - name: Copy deploy.sh
        run: scp deploy.sh ${{ secrets.LINODE_SSH_USER }}@${{ secrets.LINODE_IP }}:/home/${{ secrets.LINODE_SSH_USER }}/deploy.sh

      - name: Execute deploy.sh
        run: ssh ${{ secrets.LINODE_SSH_USER }}@${{ secrets.LINODE_IP }} "chmod +x /home/${{ secrets.LINODE_SSH_USER }}/deploy.sh && /home/${{ secrets.LINODE_SSH_USER }}/deploy.sh"
